# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oraganization', '0003_auto_20170402_1153'),
        ('course', '0002_auto_20170319_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oraganization.CourseOrg', verbose_name='课程机构'),
        ),
    ]
