# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('object_id', models.CharField(default='', max_length=20, primary_key=True, serialize=False, verbose_name='主键')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('user_name', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=30, verbose_name='密码')),
                ('confirm_password', models.CharField(max_length=30, verbose_name='确认密码')),
                ('text_info', models.CharField(default='', max_length=2000, verbose_name='留言')),
            ],
            options={
                'db_table': 'user_message',
                'verbose_name': '用户注册信息',
                'verbose_name_plural': '用户注册信息',
            },
        ),
    ]
