# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test_app',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.CharField(max_length=15, null=True, verbose_name='第一')),
                ('two', models.CharField(max_length=15, null=True, verbose_name='第二')),
                ('three', models.CharField(max_length=15, null=True, verbose_name='第三')),
            ],
            options={
                'verbose_name': '测试app',
                'db_table': 'test_123',
                'verbose_name_plural': '测试app',
            },
        ),
    ]
